# Generated by Django 5.0.7 on 2024-07-28 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_order_by_orders_order_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_created_by',
            new_name='created_by',
        ),
    ]
