# Generated by Django 5.0.7 on 2024-07-28 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_order_id_orders_order_number'),
        ('products', '0004_remove_product_unique_code_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_items', to='products.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.orders'),
        ),
    ]
