# Generated by Django 5.0.7 on 2024-07-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unique_code',
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=3213, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
